/**
 * All user-facing text, in one place, per language.
 * Rules (Pulse4all-Style.md section 4): sentence case, no all-caps, no
 * exclamation marks, no period after a title, no backend mechanics in copy.
 * The copy verifier checks these rules against this file.
 */
export type Locale = "en" | "nl";

/** Deep string shape; keeps the type structural so both languages share it */
type Deep<T> = { [K in keyof T]: T[K] extends string ? string : Deep<T[K]> };

const en = {
  app: {
    name: "Workspace",
    tagline: "Pulse4all contact center",
  },
  nav: {
    myDay: "My day",
    myHours: "My hours",
    teamHours: "Team hours",
    logOut: "Log out",
  },
  shell: {
    signedInAs: "Signed in as",
    shortcutsHint: "Number keys switch pages, S picks a status on My day, L logs out, Esc closes a dialog",
    version: "Version",
    testData: "Test data: nothing you do here is saved",
  },
  myDay: {
    title: "My day",
    working: "Working",
    workingSince: "since",
    workedToday: "Worked today",
    endWorkday: "End workday",
    confirmTitle: "End your workday",
    confirmBody: "Your clock stops now. A new workday starts when you log in tomorrow.",
    confirmYes: "End workday",
    confirmNo: "Keep working",
    dayEnded: "Your workday has ended",
    dayEndedBody: "Thanks for today. Log out when you leave, or close this tab.",
    endedAt: "Ended at",
    statusLabel: "Status",
    statusFailed: "Your status could not be changed. Try again.",
    startedAt: "Started at",
  },
  myHours: {
    title: "My hours",
    ownHoursOnly: "These are your own hours. Your supervisor sees the same figures.",
    today: "Today",
    week: "This week",
    month: "This month",
    custom: "Custom range",
    from: "From",
    to: "To",
    show: "Show",
    date: "Date",
    start: "Start",
    end: "End",
    duration: "Duration",
    total: "Total",
    stillWorking: "still working",
    empty: "No hours in this period yet",
    invalidRange: "Choose a start date on or before the end date",
  },
  teamHours: {
    title: "Team hours",
    intro: "Clock-in and clock-out per person per day, each in the person's own time zone. Worked counts working statuses, paid counts paid statuses.",
    person: "Person",
    everyone: "Everyone",
    employer: "Employer",
    date: "Date",
    clockedIn: "Clocked in",
    clockedOut: "Clocked out",
    worked: "Worked",
    paid: "Paid",
    notes: "Notes",
    total: "Total",
    correct: "Correct",
    addDay: "Add day",
    stillClockedIn: "Still clocked in",
    notClockedOut: "Not clocked out",
    needsCorrection: "Needs a correction",
    corrected: "Corrected afterwards",
    ownDay: "Someone else corrects your own day",
    keysHint: "Down or Up enters the table, the arrows choose a day, Enter opens it, A adds a day",
    empty: "No hours in this period",
    tooLong: "Choose a period of at most 92 days",
    noPermissionTitle: "Team hours are for supervisors",
    noPermissionBody: "Ask your manager if you need to see or correct the hours of your team.",
  },
  exports: {
    downloadHours: "Download hours",
    downloadStatusChanges: "Download status changes",
    hint: "Spreadsheet files for the period and person shown, in your organisation's format",
    date: "Date",
    person: "Person",
    employer: "Employer",
    timeZone: "Time zone",
    clockedIn: "Clocked in",
    clockedOut: "Clocked out",
    worked: "Worked",
    paid: "Paid",
    billable: "Billable",
    notClockedOut: "Not clocked out",
    corrected: "Corrected afterwards",
    status: "Status",
    from: "From",
    to: "To",
    duration: "Duration",
    working: "Working",
    enteredBy: "Entered by",
    sourceUser: "Person",
    sourceSystem: "System",
    sourceCorrection: "Correction",
    yes: "Yes",
    no: "No",
  },
  dayEditor: {
    correctTitle: "Correct a day",
    addTitle: "Add day",
    addIntro: "For someone who did not clock in at all. Choose the person and the date, then enter the day.",
    person: "Person",
    choosePerson: "Choose a person",
    date: "Date",
    open: "Open the day",
    timesIn: "Times in",
    loading: "Loading the day",
    loadFailed: "The day could not be loaded. Close this window and try again.",
    existingDay: "This person already has a day on this date. You are correcting that day.",
    newDay: "No day yet on this date. The first row is the clock-in.",
    time: "Time",
    status: "Status",
    clockedOut: "Clocked out",
    startLabel: "Clock-in",
    remove: "Remove",
    addRow: "Add row",
    firstTime: "first time",
    secondTime: "second time",
    reason: "Reason",
    reasonHint: "Required. It is kept with every change, together with your name.",
    save: "Save correction",
    cancel: "Cancel",
    history: "History of this day",
    byPerson: "Clocked by the person",
    bySystem: "Set by the system",
    byCorrection: "Correction by",
    replaced: "Replaced",
    cancelledRow: "Removed by a correction",
    problemTime: "Enter a time as hh:mm",
    problemGap: "This time does not exist on this date because of the clock change",
    problemAmbiguous: "This time occurs twice on this date because of the clock change. Choose which one.",
    problemFuture: "This time lies in the future",
    problemStatus: "Choose a status",
    problemEmpty: "Add at least the clock-in",
    problemFirstIsEnd: "The first row cannot be the clock-out",
    problemTwoEnds: "A day has at most one clock-out",
    problemEndNotLast: "Nothing can come after the clock-out",
    problemNoChange: "Nothing has changed yet",
    problemReason: "Give a reason of 3 to 500 characters",
    saveFailed: "The correction was not saved. Check the times and try again.",
    notPermitted: "You are not allowed to correct this day.",
    notFound: "This person or status no longer exists. Close this window and reload the page.",
    conflict: "The day changed meanwhile. Close this window and open the day again.",
    unsaved: "You have unsaved changes. Press Esc again to discard them.",
  },
  logOut: {
    title: "Log out",
    body: "This ends your workday and signs you out of the Workspace.",
    bodyDayEnded: "Your workday has already ended. This signs you out of the Workspace.",
    confirm: "Log out",
    cancel: "Stay",
    doneTitle: "You are logged out",
    doneBody: "You can close this tab. Logging in again tomorrow starts your next workday.",
    doneBodyToday: "Your workday has ended for today. You can close this tab.",
  },
  noAccess: {
    title: "No access yet",
    body: "Your Pulse4all account is recognised, but it is not set up for the Workspace yet.",
    next: "Ask your supervisor to add you. You can close this tab.",
  },
  desktopOnly: {
    title: "The Workspace needs a wider screen",
    body: "Open it on a desktop or laptop with a window of at least 1280 pixels wide.",
  },
} satisfies Record<string, Record<string, string>>;

export type Copy = Deep<typeof en>;

const nl: Copy = {
  app: {
    name: "Workspace",
    tagline: "Pulse4all contactcenter",
  },
  nav: {
    myDay: "Mijn dag",
    myHours: "Mijn uren",
    teamHours: "Teamuren",
    logOut: "Uitloggen",
  },
  shell: {
    signedInAs: "Ingelogd als",
    shortcutsHint: "Cijfertoetsen wisselen van pagina, S kiest een status op Mijn dag, L logt uit, Esc sluit een venster",
    version: "Versie",
    testData: "Testgegevens: niets wat je hier doet wordt bewaard",
  },
  myDay: {
    title: "Mijn dag",
    working: "Aan het werk",
    workingSince: "sinds",
    workedToday: "Vandaag gewerkt",
    endWorkday: "Werkdag beëindigen",
    confirmTitle: "Je werkdag beëindigen",
    confirmBody: "Je klok stopt nu. Een nieuwe werkdag begint als je morgen inlogt.",
    confirmYes: "Werkdag beëindigen",
    confirmNo: "Doorwerken",
    dayEnded: "Je werkdag is beëindigd",
    dayEndedBody: "Bedankt voor vandaag. Log uit als je weggaat, of sluit dit tabblad.",
    endedAt: "Beëindigd om",
    statusLabel: "Status",
    statusFailed: "Je status kon niet worden gewijzigd. Probeer het opnieuw.",
    startedAt: "Gestart om",
  },
  myHours: {
    title: "Mijn uren",
    ownHoursOnly: "Dit zijn je eigen uren. Je supervisor ziet dezelfde cijfers.",
    today: "Vandaag",
    week: "Deze week",
    month: "Deze maand",
    custom: "Eigen periode",
    from: "Van",
    to: "Tot en met",
    show: "Toon",
    date: "Datum",
    start: "Start",
    end: "Einde",
    duration: "Duur",
    total: "Totaal",
    stillWorking: "nog aan het werk",
    empty: "Nog geen uren in deze periode",
    invalidRange: "Kies een startdatum op of voor de einddatum",
  },
  teamHours: {
    title: "Teamuren",
    intro: "In- en uitklokken per persoon per dag, steeds in de tijdzone van die persoon. Gewerkt telt werkende statussen, betaald telt betaalde statussen.",
    person: "Persoon",
    everyone: "Iedereen",
    employer: "Werkgever",
    date: "Datum",
    clockedIn: "Ingeklokt",
    clockedOut: "Uitgeklokt",
    worked: "Gewerkt",
    paid: "Betaald",
    notes: "Notities",
    total: "Totaal",
    correct: "Corrigeren",
    addDay: "Dag toevoegen",
    stillClockedIn: "Nog ingeklokt",
    notClockedOut: "Niet uitgeklokt",
    needsCorrection: "Correctie nodig",
    corrected: "Achteraf gecorrigeerd",
    ownDay: "Je eigen dag corrigeert iemand anders",
    keysHint: "Pijl omlaag of omhoog gaat naar de tabel, de pijlen kiezen een dag, Enter opent hem, A voegt een dag toe",
    empty: "Geen uren in deze periode",
    tooLong: "Kies een periode van maximaal 92 dagen",
    noPermissionTitle: "Teamuren zijn voor supervisors",
    noPermissionBody: "Vraag je manager als je de uren van je team moet zien of corrigeren.",
  },
  exports: {
    downloadHours: "Uren downloaden",
    downloadStatusChanges: "Statuswisselingen downloaden",
    hint: "Spreadsheetbestanden voor de getoonde periode en persoon, in het formaat van je organisatie",
    date: "Datum",
    person: "Persoon",
    employer: "Werkgever",
    timeZone: "Tijdzone",
    clockedIn: "Ingeklokt",
    clockedOut: "Uitgeklokt",
    worked: "Gewerkt",
    paid: "Betaald",
    billable: "Factureerbaar",
    notClockedOut: "Niet uitgeklokt",
    corrected: "Achteraf gecorrigeerd",
    status: "Status",
    from: "Van",
    to: "Tot",
    duration: "Duur",
    working: "Werkend",
    enteredBy: "Ingevoerd door",
    sourceUser: "Persoon",
    sourceSystem: "Systeem",
    sourceCorrection: "Correctie",
    yes: "Ja",
    no: "Nee",
  },
  dayEditor: {
    correctTitle: "Een dag corrigeren",
    addTitle: "Dag toevoegen",
    addIntro: "Voor iemand die helemaal niet heeft ingeklokt. Kies de persoon en de datum en vul daarna de dag in.",
    person: "Persoon",
    choosePerson: "Kies een persoon",
    date: "Datum",
    open: "Dag openen",
    timesIn: "Tijden in",
    loading: "De dag wordt geladen",
    loadFailed: "De dag kon niet worden geladen. Sluit dit venster en probeer het opnieuw.",
    existingDay: "Deze persoon heeft al een dag op deze datum. Je corrigeert die dag.",
    newDay: "Nog geen dag op deze datum. De eerste regel is het inklokken.",
    time: "Tijd",
    status: "Status",
    clockedOut: "Uitgeklokt",
    startLabel: "Inklokken",
    remove: "Verwijderen",
    addRow: "Regel toevoegen",
    firstTime: "eerste keer",
    secondTime: "tweede keer",
    reason: "Reden",
    reasonHint: "Verplicht. De reden wordt bij elke wijziging bewaard, samen met je naam.",
    save: "Correctie opslaan",
    cancel: "Annuleren",
    history: "Geschiedenis van deze dag",
    byPerson: "Geklokt door de persoon",
    bySystem: "Gezet door het systeem",
    byCorrection: "Correctie door",
    replaced: "Vervangen",
    cancelledRow: "Verwijderd door een correctie",
    problemTime: "Vul een tijd in als uu:mm",
    problemGap: "Deze tijd bestaat niet op deze datum door de klokwisseling",
    problemAmbiguous: "Deze tijd komt twee keer voor op deze datum door de klokwisseling. Kies welke.",
    problemFuture: "Deze tijd ligt in de toekomst",
    problemStatus: "Kies een status",
    problemEmpty: "Voeg minstens het inklokken toe",
    problemFirstIsEnd: "De eerste regel kan niet het uitklokken zijn",
    problemTwoEnds: "Een dag heeft hooguit één keer uitklokken",
    problemEndNotLast: "Na het uitklokken kan niets meer komen",
    problemNoChange: "Er is nog niets gewijzigd",
    problemReason: "Geef een reden van 3 tot 500 tekens",
    saveFailed: "De correctie is niet opgeslagen. Controleer de tijden en probeer het opnieuw.",
    notPermitted: "Je mag deze dag niet corrigeren.",
    notFound: "Deze persoon of status bestaat niet meer. Sluit dit venster en laad de pagina opnieuw.",
    conflict: "De dag is intussen gewijzigd. Sluit dit venster en open de dag opnieuw.",
    unsaved: "Je hebt niet-opgeslagen wijzigingen. Druk nogmaals op Esc om ze te verwerpen.",
  },
  logOut: {
    title: "Uitloggen",
    body: "Dit beëindigt je werkdag en logt je uit bij de Workspace.",
    bodyDayEnded: "Je werkdag is al beëindigd. Dit logt je uit bij de Workspace.",
    confirm: "Uitloggen",
    cancel: "Blijven",
    doneTitle: "Je bent uitgelogd",
    doneBody: "Je kunt dit tabblad sluiten. Morgen opnieuw inloggen start je volgende werkdag.",
    doneBodyToday: "Je werkdag is beëindigd voor vandaag. Je kunt dit tabblad sluiten.",
  },
  noAccess: {
    title: "Nog geen toegang",
    body: "Je Pulse4all-account is herkend, maar is nog niet ingericht voor de Workspace.",
    next: "Vraag je supervisor om je toe te voegen. Je kunt dit tabblad sluiten.",
  },
  desktopOnly: {
    title: "De Workspace heeft een breder scherm nodig",
    body: "Open hem op een desktop of laptop met een venster van minstens 1280 pixels breed.",
  },
};

export const copy: Record<Locale, Copy> = { en, nl };
export function t(locale: Locale): Copy {
  return copy[locale];
}
