/**
 * All user-facing text, in one place, per language.
 * Rules (Pulse4all-Style.md section 4): sentence case, no all-caps, no
 * exclamation marks, no period after a title, no backend mechanics in copy.
 * The copy verifier checks these rules against this file.
 */
export type Locale = "en" | "nl";

/** Deep string shape; keeps the type structural so both languages share it */
type Deep<T> = { [K in keyof T]: T[K] extends string ? string : Deep<T[K]> };

const en = {
  app: {
    name: "Workspace",
    tagline: "Pulse4all contact center",
  },
  nav: {
    welcome: "Welcome",
    live: "Live",
    liveBoard: "Live board",
    team: "Team",
    people: "People",
    time: "Time",
    myDay: "My day",
    myHours: "My hours",
    teamHours: "Team hours",
    reports: "Reports",
    dashboard: "Dashboard",
    logOut: "Log out",
  },
  shell: {
    signedInAs: "Signed in as",
    shortcutsHint: "Number keys switch pages, S picks a status on My day, G, E and T filter the Live board, A adds a person on People, L logs out, Esc closes a dialog",
    version: "Version",
    testData: "Test data: nothing you do here is saved",
  },
  welcome: {
    morning: "Good morning, {name}",
    afternoon: "Good afternoon, {name}",
    evening: "Good evening, {name}",
    notClockedIn: "Not clocked in",
    clockInBody: "Clock in to start your day. Your status will be set to {status}.",
    clockIn: "Clock in",
    clockInFailed: "You could not be clocked in. Try again.",
    clockedIn: "Clocked in",
    clockedInAt: "Clocked in at",
    workedSoFar: "worked so far",
    dayEnded: "Your workday has ended",
    clockedOutAt: "Clocked out at",
    openMyDay: "Open My day",
    updates: "Updates",
    updatesEmpty: "No updates yet. Messages from your supervisor will appear here.",
    todo: "Before today's shift",
    notClockedOut: "{n} days in the last 31 days were not clocked out",
    notClockedOutOne: "1 day in the last 31 days was not clocked out",
    notClockedOutNone: "Every day in the last 31 days was clocked out",
    openTeamHours: "Open Team hours",
    reports: "Reports",
    reportsBody: "Where the team's time goes, per status, per day and per person.",
    openDashboard: "Open the Dashboard",
    apps: "Your applications",
    appsHint: "Each opens in a new tab",
  },
  myDay: {
    title: "My day",
    working: "Working",
    workingSince: "since",
    workedToday: "Worked today",
    endWorkday: "End workday",
    confirmTitle: "End your workday",
    confirmBody: "Your clock stops now. Your next workday starts when you clock in tomorrow.",
    confirmYes: "End workday",
    confirmNo: "Keep working",
    dayEnded: "Your workday has ended",
    dayEndedBody: "Thanks for today. Log out when you leave, or close this tab.",
    endedAt: "Ended at",
    statusLabel: "Status",
    statusFailed: "Your status could not be changed. Try again.",
    startedAt: "Started at",
  },
  myHours: {
    title: "My hours",
    ownHoursOnly: "These are your own hours. Your supervisor sees the same figures.",
    today: "Today",
    week: "This week",
    month: "This month",
    custom: "Custom range",
    from: "From",
    to: "To",
    show: "Show",
    date: "Date",
    start: "Start",
    end: "End",
    duration: "Duration",
    total: "Total",
    stillWorking: "still working",
    empty: "No hours in this period yet",
    invalidRange: "Choose a start date on or before the end date",
  },
  teamHours: {
    title: "Team hours",
    intro: "Clock-in and clock-out per person per day, each in the person's own time zone. Worked counts working statuses, paid counts paid statuses.",
    person: "Person",
    everyone: "Everyone",
    employer: "Employer",
    date: "Date",
    clockedIn: "Clocked in",
    clockedOut: "Clocked out",
    worked: "Worked",
    paid: "Paid",
    notes: "Notes",
    total: "Total",
    correct: "Correct",
    addDay: "Add day",
    stillClockedIn: "Still clocked in",
    notClockedOut: "Not clocked out",
    needsCorrection: "Needs a correction",
    corrected: "Corrected afterwards",
    ownDay: "Someone else corrects your own day",
    keysHint: "Down or Up enters the table, the arrows choose a day, Enter opens it, A adds a day",
    empty: "No hours in this period",
    tooLong: "Choose a period of at most 92 days",
    noPermissionTitle: "Team hours are for supervisors",
    noPermissionBody: "Ask your manager if you need to see or correct the hours of your team.",
  },
  exports: {
    downloadHours: "Download hours",
    downloadStatusChanges: "Download status changes",
    hint: "Spreadsheet files for the period and person shown, in your organisation's format",
    date: "Date",
    person: "Person",
    employer: "Employer",
    timeZone: "Time zone",
    clockedIn: "Clocked in",
    clockedOut: "Clocked out",
    worked: "Worked",
    paid: "Paid",
    billable: "Billable",
    notClockedOut: "Not clocked out",
    corrected: "Corrected afterwards",
    status: "Status",
    from: "From",
    to: "To",
    duration: "Duration",
    working: "Working",
    enteredBy: "Entered by",
    sourceUser: "Person",
    sourceSystem: "System",
    sourceCorrection: "Correction",
    yes: "Yes",
    no: "No",
  },
  dashboard: {
    title: "Dashboard",
    intro: "Where the team's time went, from clock-in to clock-out, grouped by what each status counts as. Each day counts in the person's own time zone.",
    person: "Person",
    everyone: "Everyone",
    period: "Period",
    worked: "Worked",
    workedHint: "Working statuses",
    paid: "Paid",
    paidHint: "Paid statuses",
    productive: "Productive",
    productiveHint: "{time} of worked time",
    people: "People",
    peopleHint: "{n} days with hours",
    peopleHintOne: "1 day with hours",
    groups: "Groups",
    byStatus: "Time per status",
    byStatusHint: "Share of the time between clock-in and clock-out",
    byDay: "Hours per day",
    byDayLabel: "Hours per day, stacked by group",
    byPerson: "Per person",
    byPersonHint: "By name. Worked and paid as in Team hours",
    status: "Status",
    time: "Time",
    share: "Share",
    inactive: "Inactive",
    employer: "Employer",
    groupProductive: "Productive",
    groupProductiveHint: "Working and productive statuses",
    groupOtherWork: "Other work",
    groupOtherWorkHint: "Working statuses that are not productive, such as training or meetings",
    groupPaidPause: "Paid pause",
    groupPaidPauseHint: "Paid statuses that stop the clock",
    groupUnpaidPause: "Unpaid pause",
    groupUnpaidPauseHint: "Unpaid statuses that stop the clock",
    cappedNote: "{n} days in this period were not clocked out. Their time stops at the end of the day until someone corrects it in Team hours.",
    cappedNoteOne: "1 day in this period was not clocked out. Its time stops at the end of the day until someone corrects it in Team hours.",
    empty: "No time recorded in this period",
    tooLong: "Choose a period of at most 92 days",
    noPermissionTitle: "The dashboard is for supervisors, managers and analysts",
    noPermissionBody: "Ask your manager if you need to see where your team's time goes.",
  },
  live: {
    title: "Live board",
    intro: "Who is on the clock right now, in which status and for how long. Today only, in each person's own time zone; earlier days that were not clocked out are on Team hours.",
    refreshHint: "Updates every 10 seconds while this tab is open",
    clockedOut: "Clocked out",
    clockedOutHint: "Today's day has ended",
    notClockedIn: "Not clocked in",
    notClockedInHint: "No day today yet",
    group: "Group",
    allGroups: "All groups",
    employer: "Employer",
    allEmployers: "All employers",
    team: "Team",
    allTeams: "All teams",
    person: "Person",
    status: "Status",
    since: "Since",
    clockedInAt: "Clocked in",
    workedSoFar: "Worked so far",
    inactive: "Inactive",
    peopleShown: "{n} of {total} people",
    empty: "Nobody matches this filter",
    noPeople: "Nobody's time is kept yet",
    noPermissionTitle: "The Live board is for supervisors, managers and analysts",
    noPermissionBody: "Ask your manager if you need to see who is on the clock.",
  },
  team: {
    title: "People",
    intro: "Everyone with access to the Workspace in this business line, with role, employer, teams and skills. A manager edits agents and supervisors; an admin edits everyone. Your own entry is changed by another admin.",
    noPermissionTitle: "People is for managers and admins",
    noPermissionBody: "Ask your manager if someone needs access, a different role, a team or a skill.",
    person: "Person",
    employer: "Employer",
    role: "Role",
    noRole: "No role yet",
    teams: "Teams",
    noTeams: "No team",
    skills: "Skills",
    noSkills: "No skills recorded",
    status: "Status",
    active: "Active",
    inactive: "Inactive",
    clockKept: "Clock",
    noClock: "No clock",
    managing: "Manages people",
    edit: "Edit",
    notEditable: "Only an admin can edit this person",
    self: "This is you",
    add: "Add a person",
    showInactive: "Show inactive",
    hideInactive: "Hide inactive",
    teamFilter: "Team",
    allTeams: "All teams",
    peopleShown: "{n} of {total} people",
    empty: "Nobody matches this filter",
    addTitle: "Add a person",
    addIntro: "The person has access as soon as they sign in. The account id comes from the sign-in provider, never from the email address.",
    editTitle: "Edit person",
    name: "Name",
    email: "Email",
    chooseEmployer: "Choose an employer",
    chooseRole: "Choose a role",
    loginSystem: "Sign-in provider",
    loginId: "Account id at the provider",
    loginIdHint: "The stable account id, digits only for a Google Workspace account. It is stored once and never shown again.",
    timeZone: "Time zone",
    timeZoneHint: "Leave empty to follow the employer",
    levelNone: "None",
    holds: "Yes",
    holdsNot: "No",
    skillsHint: "Languages carry a level; work types are held or not.",
    skillsNotPermitted: "Skills are changed by a manager with the skills permission",
    save: "Save",
    cancel: "Cancel",
    saving: "Saving",
    problemName: "Enter a name of 1 to 100 characters",
    problemEmail: "Enter an email address",
    problemLogin: "Enter the account id, without spaces",
    problemRole: "Choose a role",
    problemEmployer: "Choose an employer",
    problemNoChange: "Nothing has changed yet",
    saveFailed: "The change was not saved. Try again.",
    conflict: "This person or account id already exists with other details. Nothing was changed.",
    notPermitted: "You are not allowed to make this change.",
    notFound: "This person, role, team or skill no longer exists. Reload the page.",
    unsaved: "You have unsaved changes. Press Esc again to discard them.",
    roleHint: "One role per person. Roles that manage people are assigned by an admin.",
    activeHint: "An inactive person keeps their history and cannot use the Workspace",
  },
  dayEditor: {
    correctTitle: "Correct a day",
    addTitle: "Add day",
    addIntro: "For someone who did not clock in at all. Choose the person and the date, then enter the day.",
    person: "Person",
    choosePerson: "Choose a person",
    date: "Date",
    open: "Open the day",
    timesIn: "Times in",
    loading: "Loading the day",
    loadFailed: "The day could not be loaded. Close this window and try again.",
    existingDay: "This person already has a day on this date. You are correcting that day.",
    newDay: "No day yet on this date. The first row is the clock-in.",
    time: "Time",
    status: "Status",
    clockedOut: "Clocked out",
    inactiveStatus: "no longer in use",
    startLabel: "Clock-in",
    remove: "Remove",
    addRow: "Add row",
    firstTime: "first time",
    secondTime: "second time",
    reason: "Reason",
    reasonHint: "Required. It is kept with every change, together with your name.",
    save: "Save correction",
    cancel: "Cancel",
    history: "History of this day",
    byPerson: "Clocked by the person",
    bySystem: "Set by the system",
    byCorrection: "Correction by",
    replaced: "Replaced",
    cancelledRow: "Removed by a correction",
    problemTime: "Enter a time as hh:mm",
    problemGap: "This time does not exist on this date because of the clock change",
    problemAmbiguous: "This time occurs twice on this date because of the clock change. Choose which one.",
    problemFuture: "This time lies in the future",
    problemStatus: "Choose a status",
    problemInactive: "This status is no longer in use. A changed row needs a current status.",
    problemEmpty: "Add at least the clock-in",
    problemFirstIsEnd: "The first row cannot be the clock-out",
    problemTwoEnds: "A day has at most one clock-out",
    problemEndNotLast: "Nothing can come after the clock-out",
    problemNoChange: "Nothing has changed yet",
    problemReason: "Give a reason of 3 to 500 characters",
    saveFailed: "The correction was not saved. Check the times and try again.",
    notPermitted: "You are not allowed to correct this day.",
    notFound: "This person or status no longer exists. Close this window and reload the page.",
    conflict: "The day changed meanwhile. Close this window and open the day again.",
    unsaved: "You have unsaved changes. Press Esc again to discard them.",
  },
  logOut: {
    title: "Log out",
    body: "This ends your workday and signs you out of the Workspace.",
    bodyDayEnded: "Your workday has already ended. This signs you out of the Workspace.",
    confirm: "Log out",
    cancel: "Stay",
    doneTitle: "You are logged out",
    doneBody: "You can close this tab. Your next workday starts when you clock in tomorrow.",
    doneBodyToday: "Your workday has ended for today. You can close this tab.",
  },
  noAccess: {
    title: "No access yet",
    body: "Your Pulse4all account is recognised, but it is not set up for the Workspace yet.",
    next: "Ask your supervisor to add you. You can close this tab.",
  },
  desktopOnly: {
    title: "The Workspace needs a wider screen",
    body: "Open it on a desktop or laptop with a window of at least 1280 pixels wide.",
  },
} satisfies Record<string, Record<string, string>>;

export type Copy = Deep<typeof en>;

const nl: Copy = {
  app: {
    name: "Workspace",
    tagline: "Pulse4all contactcenter",
  },
  nav: {
    welcome: "Welkom",
    live: "Live",
    liveBoard: "Livebord",
    team: "Team",
    people: "Mensen",
    time: "Tijd",
    myDay: "Mijn dag",
    myHours: "Mijn uren",
    teamHours: "Teamuren",
    reports: "Rapportages",
    dashboard: "Dashboard",
    logOut: "Uitloggen",
  },
  shell: {
    signedInAs: "Ingelogd als",
    shortcutsHint: "Cijfertoetsen wisselen van pagina, S kiest een status op Mijn dag, G, E en T filteren het livebord, A voegt iemand toe op Mensen, L logt uit, Esc sluit een venster",
    version: "Versie",
    testData: "Testgegevens: niets wat je hier doet wordt bewaard",
  },
  welcome: {
    morning: "Goedemorgen, {name}",
    afternoon: "Goedemiddag, {name}",
    evening: "Goedenavond, {name}",
    notClockedIn: "Niet ingeklokt",
    clockInBody: "Klok in om je dag te beginnen. Je status wordt dan {status}.",
    clockIn: "Inklokken",
    clockInFailed: "Je kon niet worden ingeklokt. Probeer het opnieuw.",
    clockedIn: "Ingeklokt",
    clockedInAt: "Ingeklokt om",
    workedSoFar: "tot nu toe gewerkt",
    dayEnded: "Je werkdag is beëindigd",
    clockedOutAt: "Uitgeklokt om",
    openMyDay: "Open Mijn dag",
    updates: "Updates",
    updatesEmpty: "Nog geen updates. Berichten van je supervisor verschijnen hier.",
    todo: "Voor de dienst van vandaag",
    notClockedOut: "{n} dagen in de laatste 31 dagen zijn niet uitgeklokt",
    notClockedOutOne: "1 dag in de laatste 31 dagen is niet uitgeklokt",
    notClockedOutNone: "Elke dag in de laatste 31 dagen is uitgeklokt",
    openTeamHours: "Open Teamuren",
    reports: "Rapportages",
    reportsBody: "Waar de tijd van het team naartoe gaat, per status, per dag en per persoon.",
    openDashboard: "Open het Dashboard",
    apps: "Je applicaties",
    appsHint: "Elke opent in een nieuw tabblad",
  },
  myDay: {
    title: "Mijn dag",
    working: "Aan het werk",
    workingSince: "sinds",
    workedToday: "Vandaag gewerkt",
    endWorkday: "Werkdag beëindigen",
    confirmTitle: "Je werkdag beëindigen",
    confirmBody: "Je klok stopt nu. Je volgende werkdag begint als je morgen inklokt.",
    confirmYes: "Werkdag beëindigen",
    confirmNo: "Doorwerken",
    dayEnded: "Je werkdag is beëindigd",
    dayEndedBody: "Bedankt voor vandaag. Log uit als je weggaat, of sluit dit tabblad.",
    endedAt: "Beëindigd om",
    statusLabel: "Status",
    statusFailed: "Je status kon niet worden gewijzigd. Probeer het opnieuw.",
    startedAt: "Gestart om",
  },
  myHours: {
    title: "Mijn uren",
    ownHoursOnly: "Dit zijn je eigen uren. Je supervisor ziet dezelfde cijfers.",
    today: "Vandaag",
    week: "Deze week",
    month: "Deze maand",
    custom: "Eigen periode",
    from: "Van",
    to: "Tot en met",
    show: "Toon",
    date: "Datum",
    start: "Start",
    end: "Einde",
    duration: "Duur",
    total: "Totaal",
    stillWorking: "nog aan het werk",
    empty: "Nog geen uren in deze periode",
    invalidRange: "Kies een startdatum op of voor de einddatum",
  },
  teamHours: {
    title: "Teamuren",
    intro: "In- en uitklokken per persoon per dag, steeds in de tijdzone van die persoon. Gewerkt telt werkende statussen, betaald telt betaalde statussen.",
    person: "Persoon",
    everyone: "Iedereen",
    employer: "Werkgever",
    date: "Datum",
    clockedIn: "Ingeklokt",
    clockedOut: "Uitgeklokt",
    worked: "Gewerkt",
    paid: "Betaald",
    notes: "Notities",
    total: "Totaal",
    correct: "Corrigeren",
    addDay: "Dag toevoegen",
    stillClockedIn: "Nog ingeklokt",
    notClockedOut: "Niet uitgeklokt",
    needsCorrection: "Correctie nodig",
    corrected: "Achteraf gecorrigeerd",
    ownDay: "Je eigen dag corrigeert iemand anders",
    keysHint: "Pijl omlaag of omhoog gaat naar de tabel, de pijlen kiezen een dag, Enter opent hem, A voegt een dag toe",
    empty: "Geen uren in deze periode",
    tooLong: "Kies een periode van maximaal 92 dagen",
    noPermissionTitle: "Teamuren zijn voor supervisors",
    noPermissionBody: "Vraag je manager als je de uren van je team moet zien of corrigeren.",
  },
  exports: {
    downloadHours: "Uren downloaden",
    downloadStatusChanges: "Statuswisselingen downloaden",
    hint: "Spreadsheetbestanden voor de getoonde periode en persoon, in het formaat van je organisatie",
    date: "Datum",
    person: "Persoon",
    employer: "Werkgever",
    timeZone: "Tijdzone",
    clockedIn: "Ingeklokt",
    clockedOut: "Uitgeklokt",
    worked: "Gewerkt",
    paid: "Betaald",
    billable: "Factureerbaar",
    notClockedOut: "Niet uitgeklokt",
    corrected: "Achteraf gecorrigeerd",
    status: "Status",
    from: "Van",
    to: "Tot",
    duration: "Duur",
    working: "Werkend",
    enteredBy: "Ingevoerd door",
    sourceUser: "Persoon",
    sourceSystem: "Systeem",
    sourceCorrection: "Correctie",
    yes: "Ja",
    no: "Nee",
  },
  dashboard: {
    title: "Dashboard",
    intro: "Waar de tijd van het team naartoe ging, van inklokken tot uitklokken, gegroepeerd naar wat elke status telt. Elke dag telt in de tijdzone van de persoon zelf.",
    person: "Persoon",
    everyone: "Iedereen",
    period: "Periode",
    worked: "Gewerkt",
    workedHint: "Werkende statussen",
    paid: "Betaald",
    paidHint: "Betaalde statussen",
    productive: "Productief",
    productiveHint: "{time} van de gewerkte tijd",
    people: "Mensen",
    peopleHint: "{n} dagen met uren",
    peopleHintOne: "1 dag met uren",
    groups: "Groepen",
    byStatus: "Tijd per status",
    byStatusHint: "Aandeel van de tijd tussen inklokken en uitklokken",
    byDay: "Uren per dag",
    byDayLabel: "Uren per dag, gestapeld per groep",
    byPerson: "Per persoon",
    byPersonHint: "Op naam. Gewerkt en betaald zoals in Teamuren",
    status: "Status",
    time: "Tijd",
    share: "Aandeel",
    inactive: "Inactief",
    employer: "Werkgever",
    groupProductive: "Productief",
    groupProductiveHint: "Werkende en productieve statussen",
    groupOtherWork: "Ander werk",
    groupOtherWorkHint: "Werkende statussen die niet productief zijn, zoals training of overleg",
    groupPaidPause: "Betaalde pauze",
    groupPaidPauseHint: "Betaalde statussen die de klok stilzetten",
    groupUnpaidPause: "Onbetaalde pauze",
    groupUnpaidPauseHint: "Onbetaalde statussen die de klok stilzetten",
    cappedNote: "{n} dagen in deze periode zijn niet uitgeklokt. Hun tijd stopt aan het eind van de dag tot iemand ze corrigeert in Teamuren.",
    cappedNoteOne: "1 dag in deze periode is niet uitgeklokt. De tijd stopt aan het eind van de dag tot iemand hem corrigeert in Teamuren.",
    empty: "Geen tijd geregistreerd in deze periode",
    tooLong: "Kies een periode van maximaal 92 dagen",
    noPermissionTitle: "Het dashboard is voor supervisors, managers en analisten",
    noPermissionBody: "Vraag je manager als je wilt zien waar de tijd van je team naartoe gaat.",
  },
  live: {
    title: "Livebord",
    intro: "Wie nu is ingeklokt, in welke status en hoe lang al. Alleen vandaag, in ieders eigen tijdzone; eerdere dagen die niet zijn uitgeklokt staan op Teamuren.",
    refreshHint: "Ververst elke 10 seconden zolang dit tabblad open is",
    clockedOut: "Uitgeklokt",
    clockedOutHint: "De dag van vandaag is beëindigd",
    notClockedIn: "Niet ingeklokt",
    notClockedInHint: "Nog geen dag vandaag",
    group: "Groep",
    allGroups: "Alle groepen",
    employer: "Werkgever",
    allEmployers: "Alle werkgevers",
    team: "Team",
    allTeams: "Alle teams",
    person: "Persoon",
    status: "Status",
    since: "Sinds",
    clockedInAt: "Ingeklokt",
    workedSoFar: "Tot nu gewerkt",
    inactive: "Inactief",
    peopleShown: "{n} van {total} mensen",
    empty: "Niemand voldoet aan dit filter",
    noPeople: "Van niemand wordt nog tijd bijgehouden",
    noPermissionTitle: "Het livebord is voor supervisors, managers en analisten",
    noPermissionBody: "Vraag je manager als je wilt zien wie er is ingeklokt.",
  },
  team: {
    title: "Mensen",
    intro: "Iedereen met toegang tot de Workspace in deze businesslijn, met rol, werkgever, teams en vaardigheden. Een manager bewerkt agents en supervisors; een admin bewerkt iedereen. Je eigen gegevens worden door een andere admin gewijzigd.",
    noPermissionTitle: "Mensen is voor managers en admins",
    noPermissionBody: "Vraag je manager als iemand toegang, een andere rol, een team of een vaardigheid nodig heeft.",
    person: "Persoon",
    employer: "Werkgever",
    role: "Rol",
    noRole: "Nog geen rol",
    teams: "Teams",
    noTeams: "Geen team",
    skills: "Vaardigheden",
    noSkills: "Geen vaardigheden vastgelegd",
    status: "Status",
    active: "Actief",
    inactive: "Inactief",
    clockKept: "Klok",
    noClock: "Geen klok",
    managing: "Beheert mensen",
    edit: "Bewerken",
    notEditable: "Alleen een admin kan deze persoon bewerken",
    self: "Dit ben jij",
    add: "Iemand toevoegen",
    showInactive: "Toon inactief",
    hideInactive: "Verberg inactief",
    teamFilter: "Team",
    allTeams: "Alle teams",
    peopleShown: "{n} van {total} mensen",
    empty: "Niemand past bij dit filter",
    addTitle: "Iemand toevoegen",
    addIntro: "De persoon heeft toegang zodra hij of zij inlogt. Het account-id komt van de inlogprovider, nooit van het e-mailadres.",
    editTitle: "Persoon bewerken",
    name: "Naam",
    email: "E-mail",
    chooseEmployer: "Kies een werkgever",
    chooseRole: "Kies een rol",
    loginSystem: "Inlogprovider",
    loginId: "Account-id bij de provider",
    loginIdHint: "Het vaste account-id, alleen cijfers bij een Google Workspace-account. Het wordt één keer opgeslagen en daarna niet meer getoond.",
    timeZone: "Tijdzone",
    timeZoneHint: "Leeg laten om de werkgever te volgen",
    levelNone: "Geen",
    holds: "Ja",
    holdsNot: "Nee",
    skillsHint: "Talen hebben een niveau; werksoorten heb je wel of niet.",
    skillsNotPermitted: "Vaardigheden worden gewijzigd door een manager met de vaardighedenrechten",
    save: "Opslaan",
    cancel: "Annuleren",
    saving: "Bezig met opslaan",
    problemName: "Vul een naam in van 1 tot 100 tekens",
    problemEmail: "Vul een e-mailadres in",
    problemLogin: "Vul het account-id in, zonder spaties",
    problemRole: "Kies een rol",
    problemEmployer: "Kies een werkgever",
    problemNoChange: "Er is nog niets gewijzigd",
    saveFailed: "De wijziging is niet opgeslagen. Probeer het opnieuw.",
    conflict: "Deze persoon of dit account-id bestaat al met andere gegevens. Er is niets gewijzigd.",
    notPermitted: "Je mag deze wijziging niet maken.",
    notFound: "Deze persoon, rol, team of vaardigheid bestaat niet meer. Laad de pagina opnieuw.",
    unsaved: "Je hebt niet-opgeslagen wijzigingen. Druk nogmaals op Esc om ze te verwerpen.",
    roleHint: "Eén rol per persoon. Rollen die mensen beheren worden door een admin toegekend.",
    activeHint: "Een inactieve persoon houdt zijn geschiedenis en kan de Workspace niet gebruiken",
  },
  dayEditor: {
    correctTitle: "Een dag corrigeren",
    addTitle: "Dag toevoegen",
    addIntro: "Voor iemand die helemaal niet heeft ingeklokt. Kies de persoon en de datum en vul daarna de dag in.",
    person: "Persoon",
    choosePerson: "Kies een persoon",
    date: "Datum",
    open: "Dag openen",
    timesIn: "Tijden in",
    loading: "De dag wordt geladen",
    loadFailed: "De dag kon niet worden geladen. Sluit dit venster en probeer het opnieuw.",
    existingDay: "Deze persoon heeft al een dag op deze datum. Je corrigeert die dag.",
    newDay: "Nog geen dag op deze datum. De eerste regel is het inklokken.",
    time: "Tijd",
    status: "Status",
    clockedOut: "Uitgeklokt",
    inactiveStatus: "niet meer in gebruik",
    startLabel: "Inklokken",
    remove: "Verwijderen",
    addRow: "Regel toevoegen",
    firstTime: "eerste keer",
    secondTime: "tweede keer",
    reason: "Reden",
    reasonHint: "Verplicht. De reden wordt bij elke wijziging bewaard, samen met je naam.",
    save: "Correctie opslaan",
    cancel: "Annuleren",
    history: "Geschiedenis van deze dag",
    byPerson: "Geklokt door de persoon",
    bySystem: "Gezet door het systeem",
    byCorrection: "Correctie door",
    replaced: "Vervangen",
    cancelledRow: "Verwijderd door een correctie",
    problemTime: "Vul een tijd in als uu:mm",
    problemGap: "Deze tijd bestaat niet op deze datum door de klokwisseling",
    problemAmbiguous: "Deze tijd komt twee keer voor op deze datum door de klokwisseling. Kies welke.",
    problemFuture: "Deze tijd ligt in de toekomst",
    problemStatus: "Kies een status",
    problemInactive: "Deze status is niet meer in gebruik. Een gewijzigde regel heeft een huidige status nodig.",
    problemEmpty: "Voeg minstens het inklokken toe",
    problemFirstIsEnd: "De eerste regel kan niet het uitklokken zijn",
    problemTwoEnds: "Een dag heeft hooguit één keer uitklokken",
    problemEndNotLast: "Na het uitklokken kan niets meer komen",
    problemNoChange: "Er is nog niets gewijzigd",
    problemReason: "Geef een reden van 3 tot 500 tekens",
    saveFailed: "De correctie is niet opgeslagen. Controleer de tijden en probeer het opnieuw.",
    notPermitted: "Je mag deze dag niet corrigeren.",
    notFound: "Deze persoon of status bestaat niet meer. Sluit dit venster en laad de pagina opnieuw.",
    conflict: "De dag is intussen gewijzigd. Sluit dit venster en open de dag opnieuw.",
    unsaved: "Je hebt niet-opgeslagen wijzigingen. Druk nogmaals op Esc om ze te verwerpen.",
  },
  logOut: {
    title: "Uitloggen",
    body: "Dit beëindigt je werkdag en logt je uit bij de Workspace.",
    bodyDayEnded: "Je werkdag is al beëindigd. Dit logt je uit bij de Workspace.",
    confirm: "Uitloggen",
    cancel: "Blijven",
    doneTitle: "Je bent uitgelogd",
    doneBody: "Je kunt dit tabblad sluiten. Je volgende werkdag begint als je morgen inklokt.",
    doneBodyToday: "Je werkdag is beëindigd voor vandaag. Je kunt dit tabblad sluiten.",
  },
  noAccess: {
    title: "Nog geen toegang",
    body: "Je Pulse4all-account is herkend, maar is nog niet ingericht voor de Workspace.",
    next: "Vraag je supervisor om je toe te voegen. Je kunt dit tabblad sluiten.",
  },
  desktopOnly: {
    title: "De Workspace heeft een breder scherm nodig",
    body: "Open hem op een desktop of laptop met een venster van minstens 1280 pixels breed.",
  },
};

export const copy: Record<Locale, Copy> = { en, nl };
export function t(locale: Locale): Copy {
  return copy[locale];
}
